apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
    - image: server
      context: server
      requires:
        - image: base
          alias: BASE
    - image: worker
      context: worker
      requires:
        - image: base
          alias: BASE
    - image: base
      context: base
deploy:
  kubectl:
    manifests:
      - infra/kubernetes/*
      - server/kubernetes/*
      - worker/kubernetes/*
portForward:
  - resourceType: service
    resourceName: redis-cart
    port: 6379
    localPort: 2113
  - resourceType: service
    resourceName: server
    port: http
    localPort: 2112
# profiles:
#   - name: gcb
#     build:
#       googleCloudBuild: {}